general {
    hide_cursor = true
}

background {
    monitor =

    path =
    reload_cmd = cat $HOME/.local/state/wallpaper/current

    blur_size = 5
    blur_passes = 4
    noise = 0.01
    contrast = 1.15
    brightness = 0.75
    vibrancy = 0.20
}

input-field {
    monitor = DP-1

    size = 300, 50
    position = 0, 50

    halign = center
    valign = bottom

    rounding = 10
    outline_thickness = 2

    dots_size = 0.2
    dots_spacing = 0.64
    dots_center = true

    inner_color = rgba(363a4fff)
    outer_color = rgba(b7bdf8cc)
    font_color = rgba(cad3f5ff)

    check_color = rgba(eed49fff)
    fail_color = rgba(ed8796ff)

    placeholder_text = <i>Password...</i>
    fail_text = <i>$FAIL <b>($ATTEMPTS)</b></i>

    fade_on_empty = true
}

label {
    monitor = DP-1

    text = cmd[update:1000] echo "<b>$(date +"%H:%M")</b>"

    color = rgba(cad3f5ff)
    font_size = 64
    font_family = Maple Mono NF

    position = 0, -35
    halign = center
    valign = center
}
