-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --
-- AUTOGENERATED HYPRLAND CONFIG.                        --
-- EDIT THIS CONFIG ACCORDING TO THE WIKI INSTRUCTIONS.  --
-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- --

-- This is an example Hyprland Lua config file.
-- Refer to the wiki for more information.
-- https://wiki.hypr.land/Configuring/Start/

-- Please note not all available settings / options are set here.
-- For a full list, see the wiki

-- You can (and should!!) split this configuration into multiple files
-- Create your files separately and then require them like this:
-- require("myColors")

require("monitors")

local colors = require("themes.catppuccin-macchiato")

local function alpha(hex, opacity)
	return "rgba(" .. hex .. opacity .. ")"
end

------------------
---- MONITORS ----
------------------

-- See https://wiki.hypr.land/Configuring/Basics/Monitors/
hl.monitor({
	output = "",
	mode = "preferred",
	position = "auto",
	scale = "auto",
})

---------------------
---- MY PROGRAMS ----
---------------------

-- Set programs that you use
local terminal = "ghostty"
local fileManager = "nemo"
local music = "spotify-launcher"
local browser = "zen-browser"
local launcher = "rofi -show drun -show-icons"
local runner = "rofi -show run"
local notis = "swaync-client -t"

-------------------
---- AUTOSTART ----
-------------------

-- See https://wiki.hypr.land/Configuring/Basics/Autostart/

-- Autostart necessary processes (like notifications daemons, status bars, etc.)
-- Or execute your favorite apps at launch like this:
--
hl.on("hyprland.start", function()
	hl.exec_cmd(terminal)
	hl.exec_cmd("nm-applet")
	hl.exec_cmd("waybar")
	hl.exec_cmd("awww-daemon")
	hl.exec_cmd(browser)
	hl.exec_cmd("swaync")
	hl.exec_cmd("hyprsunset")
	hl.exec_cmd("hypridle")
end)

-------------------------------
---- ENVIRONMENT VARIABLES ----
-------------------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Environment-variables/

hl.env("XCURSOR_THEME", "catppuccin-macchiato-dark-cursors")
hl.env("XCURSOR_SIZE", "24")
hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")

-----------------------
----- PERMISSIONS -----
-----------------------

-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Permissions/
-- Please note permission changes here require a Hyprland restart and are not applied on-the-fly
-- for security reasons

-- hl.config({
--   ecosystem = {
--     enforce_permissions = true,
--   },
-- })

-- hl.permission("/usr/(bin|local/bin)/grim", "screencopy", "allow")
-- hl.permission("/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland", "screencopy", "allow")
-- hl.permission("/usr/(bin|local/bin)/hyprpm", "plugin", "allow")

-----------------------
---- LOOK AND FEEL ----
-----------------------

-- Refer to https://wiki.hypr.land/Configuring/Basics/Variables/
hl.config({
	general = {
		gaps_in = 15,
		gaps_out = 15,

		border_size = 2,

		col = {
			active_border = alpha(colors.lavenderAlpha, "e0"),
			inactive_border = alpha(colors.textAlpha, "40"),
		},

		resize_on_border = false,
		allow_tearing = false,
		layout = "dwindle",
	},

	decoration = {
		rounding = 6,

		active_opacity = 0.92,
		inactive_opacity = 0.92,
		fullscreen_opacity = 1.0,

		blur = {
			enabled = true,
			size = 5,
			passes = 4,
			ignore_opacity = true,
			new_optimizations = true,
			xray = false,
			noise = 0.0,
			popups = true,
		},

		shadow = {
			enabled = true,
			range = 60,
			render_power = 1,
			sharp = false,

			color = alpha(colors.crustAlpha, "ff"),
			color_inactive = alpha(colors.mantleAlpha, "ff"),

			offset = { 0, 20 },
			scale = 0.98,
		},

		dim_inactive = false,
		dim_strength = 0.05,
	},

	group = {
		col = {
			border_inactive = alpha(colors.lavenderAlpha, "69"),

			border_active = {
				colors = {
					alpha(colors.textAlpha, "ee"),
					alpha(colors.lavenderAlpha, "69"),
					alpha(colors.lavenderAlpha, "69"),
					alpha(colors.textAlpha, "ee"),
				},
				angle = 45,
			},

			border_locked_inactive = alpha(colors.lavenderAlpha, "69"),

			border_locked_active = {
				colors = {
					alpha(colors.textAlpha, "ee"),
					alpha(colors.lavenderAlpha, "69"),
					alpha(colors.lavenderAlpha, "69"),
					alpha(colors.textAlpha, "ee"),
				},
				angle = 45,
			},
		},

		groupbar = {
			gradients = true,
			gradient_rounding = 7,
			indicator_height = 0,
			gradient_round_only_edges = true,

			col = {
				active = alpha(colors.lavenderAlpha, "cc"),
				inactive = alpha(colors.subtext1Alpha, "99"),
				locked_active = alpha(colors.maroonAlpha, "cc"),
				locked_inactive = alpha(colors.subtext1Alpha, "99"),
			},

			font_family = "Dotfiles Mono",
			font_size = 15,
			text_color = colors.crust,
			height = 20,
		},
	},

	animations = {
		enabled = true,
	},

	misc = {
		focus_on_activate = true,
		animate_manual_resizes = true,
		font_family = "Dotfiles Mono",
	},

	dwindle = {
		preserve_split = true,
		force_split = 0,
	},
})

-- Matt-FTW animation curves
-- hl.curve("default", {
-- 	type = "bezier",
-- 	points = { { 0.05, 0.9 }, { 0.1, 1.02 } },
-- })
--
-- hl.curve("wind", {
-- 	type = "bezier",
-- 	points = { { 0.05, 0.9 }, { 0.1, 1.02 } },
-- })
--
-- hl.curve("overshot", {
-- 	type = "bezier",
-- 	points = { { 0.13, 0.99 }, { 0.29, 1.02 } },
-- })
--
-- hl.curve("liner", {
-- 	type = "bezier",
-- 	points = { { 1, 1 }, { 1, 1 } },
-- })
--
-- hl.curve("easeOutQuint", {
-- 	type = "bezier",
-- 	points = { { 0.23, 1 }, { 0.32, 1.03 } },
-- })
--
-- -- Matt-FTW fast animations
-- hl.animation({
-- 	leaf = "windows",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "easeOutQuint",
-- 	style = "popin",
-- })
--
-- hl.animation({
-- 	leaf = "windowsIn",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "easeOutQuint",
-- 	style = "popin",
-- })
--
-- hl.animation({
-- 	leaf = "windowsOut",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "overshot",
-- 	style = "popin",
-- })
--
-- hl.animation({
-- 	leaf = "windowsMove",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "overshot",
-- })
--
-- hl.animation({
-- 	leaf = "layers",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "default",
-- 	style = "popin",
-- })
--
-- hl.animation({
-- 	leaf = "fadeIn",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "default",
-- })
--
-- hl.animation({
-- 	leaf = "fadeOut",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "default",
-- })
--
-- hl.animation({
-- 	leaf = "fadeSwitch",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "default",
-- })
--
-- hl.animation({
-- 	leaf = "fadeShadow",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "default",
-- })
--
-- hl.animation({
-- 	leaf = "fadeDim",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "default",
-- })
--
-- hl.animation({
-- 	leaf = "fadeLayers",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "default",
-- })
--
-- hl.animation({
-- 	leaf = "workspaces",
-- 	enabled = true,
-- 	speed = 2,
-- 	bezier = "wind",
-- 	style = "slidevert",
-- })
--
-- hl.animation({
-- 	leaf = "border",
-- 	enabled = true,
-- 	speed = 1,
-- 	bezier = "liner",
-- })

-- Default curves and animations, see https://wiki.hypr.land/Configuring/Advanced-and-Cool/Animations/
hl.curve("easeOutQuint", { type = "bezier", points = { { 0.23, 1 }, { 0.32, 1 } } })
hl.curve("easeInOutCubic", { type = "bezier", points = { { 0.65, 0.05 }, { 0.36, 1 } } })
hl.curve("linear", { type = "bezier", points = { { 0, 0 }, { 1, 1 } } })
hl.curve("almostLinear", { type = "bezier", points = { { 0.5, 0.5 }, { 0.75, 1 } } })
hl.curve("quick", { type = "bezier", points = { { 0.15, 0 }, { 0.1, 1 } } })

-- Default springs
hl.curve("easy", { type = "spring", mass = 1, stiffness = 238.1191, dampening = 24.21279333 })

hl.animation({ leaf = "global", enabled = true, speed = 10, bezier = "default" })
hl.animation({ leaf = "border", enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows", enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn", enabled = true, speed = 4.1, spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut", enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn", enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut", enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade", enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers", enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn", enabled = true, speed = 4, bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut", enabled = true, speed = 1.5, bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn", enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn", enabled = true, speed = 1.21, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "zoomFactor", enabled = true, speed = 7, bezier = "quick" })

-- Ref https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/
-- "Smart gaps" / "No gaps when only"
-- uncomment all if you wish to use that.
-- hl.workspace_rule({ workspace = "w[tv1]", gaps_out = 0, gaps_in = 0 })
-- hl.workspace_rule({ workspace = "f[1]",   gaps_out = 0, gaps_in = 0 })
-- hl.window_rule({
--     name  = "no-gaps-wtv1",
--     match = { float = false, workspace = "w[tv1]" },
--     border_size = 0,
--     rounding    = 0,
-- })
-- hl.window_rule({
--     name  = "no-gaps-f1",
--     match = { float = false, workspace = "f[1]" },
--     border_size = 0,
--     rounding    = 0,
-- })

-- See https://wiki.hypr.land/Configuring/Layouts/Dwindle-Layout/ for more
hl.config({
	dwindle = {
		preserve_split = true, -- You probably want this
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Master-Layout/ for more
hl.config({
	master = {
		new_status = "master",
	},
})

-- See https://wiki.hypr.land/Configuring/Layouts/Scrolling-Layout/ for more
hl.config({
	scrolling = {
		fullscreen_on_one_column = true,
	},
})

hl.config({
	cursor = {
		default_monitor = "DP-1",
	},
})

----------------
----  MISC  ----
----------------

hl.config({
	misc = {
		force_default_wallpaper = -1, -- Set to 0 or 1 to disable the anime mascot wallpapers
		disable_hyprland_logo = false, -- If true disables the random hyprland logo / anime girl background. :(
	},
})

---------------
---- INPUT ----
---------------

hl.config({
	input = {
		kb_layout = "us",
		kb_variant = "",
		kb_model = "",
		kb_options = "",
		kb_rules = "",

		repeat_rate = 25,
		repeat_delay = 300,

		follow_mouse = 1,

		sensitivity = 0, -- -1.0 - 1.0, 0 means no modification.

		touchpad = {
			natural_scroll = false,
			scroll_factor = 0.2,
		},
	},
})

hl.gesture({
	fingers = 3,
	direction = "horizontal",
	action = "workspace",
})

-- Example per-device config
-- See https://wiki.hypr.land/Configuring/Advanced-and-Cool/Devices/ for more
hl.device({
	name = "epic-mouse-v1",
	sensitivity = -0.5,
})

---------------------
---- KEYBINDINGS ----
---------------------

local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local secondMod = "SUPER + SHIFT"

-- Example binds, see https://wiki.hypr.land/Configuring/Basics/Binds/ for more
hl.bind(mainMod .. " + T", hl.dsp.exec_cmd(terminal))
hl.bind(mainMod .. " + E", hl.dsp.exec_cmd(fileManager))
hl.bind(mainMod .. " + B", hl.dsp.exec_cmd(browser))
hl.bind(mainMod .. " + M", hl.dsp.exec_cmd(music))
hl.bind(mainMod .. " + N", hl.dsp.exec_cmd(notis))
hl.bind(mainMod .. " + Space", hl.dsp.exec_cmd(launcher))
hl.bind(secondMod .. " + Space", hl.dsp.exec_cmd(runner))

hl.bind(mainMod .. " + W", hl.dsp.window.close())

hl.bind(
	secondMod .. " + W",
	hl.dsp.exec_cmd("command -v hyprshutdown >/dev/null 2>&1 && hyprshutdown || hyprctl dispatch 'hl.dsp.exit()'")
)

-- hl.bind(mainMod .. " + R", hl.dsp.exec_cmd(launcher))
-- hl.bind(mainMod .. " + P", hl.dsp.window.pseudo())
-- hl.bind(mainMod .. " + J", hl.dsp.layout("togglesplit")) -- dwindle only

-- Move focus with mainMod + arrow keys
hl.bind(mainMod .. " + h", hl.dsp.focus({ direction = "left" }))
hl.bind(mainMod .. " + l", hl.dsp.focus({ direction = "right" }))
hl.bind(mainMod .. " + k", hl.dsp.focus({ direction = "up" }))
hl.bind(mainMod .. " + j", hl.dsp.focus({ direction = "down" }))

hl.bind(secondMod .. " + h", hl.dsp.window.move({ direction = "left" }))
hl.bind(secondMod .. " + l", hl.dsp.window.move({ direction = "right" }))
hl.bind(secondMod .. " + k", hl.dsp.window.move({ direction = "up" }))
hl.bind(secondMod .. " + j", hl.dsp.window.move({ direction = "down" }))

hl.bind(mainMod .. " + P", hl.dsp.window.float({ action = "toggle" }))
hl.bind(secondMod .. " + F", hl.dsp.window.fullscreen({ mode = "maximized" }))

hl.bind(
	mainMod .. " + F",
	hl.dsp.window.fullscreen({
		mode = "fullscreen",
		action = "toggle",
	}),
	{
		dont_inhibit = true,
		allow_input_capture = true,
	}
)

-- Switch workspaces with mainMod + [0-9]
-- Move active window to a workspace with mainMod + SHIFT + [0-9]
for i = 1, 10 do
	local key = i % 10 -- 10 maps to key 0
	hl.bind(mainMod .. " + " .. key, hl.dsp.focus({ workspace = i }))
	hl.bind(secondMod .. " + " .. key, hl.dsp.window.move({ workspace = i }))
end

-- Example special workspace (scratchpad)
hl.bind(mainMod .. " + O", hl.dsp.workspace.toggle_special("magic"))
hl.bind(mainMod .. " + SHIFT + O", hl.dsp.window.move({ workspace = "special:magic" }))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + mouse:273", hl.dsp.window.resize(), { mouse = true })

hl.bind(
	secondMod .. " + S",
	hl.dsp.exec_cmd("hyprshot -m region --clipboard-only"),
	{ description = "Screenshot region to clipboard" }
)

hl.bind(mainMod .. " + CTRL + L", hl.dsp.exec_cmd("pidof hyprlock || hyprlock"))

hl.bind(mainMod .. " + CTRL + P", hl.dsp.exec_cmd("~/.config/rofi/scripts/powermenu/powermenu"))

hl.bind(mainMod .. " + D", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-picker"))
hl.bind(secondMod .. " + D", hl.dsp.exec_cmd("~/.config/hypr/scripts/wallpaper-random"))

-- Scrolling layout controls
hl.bind(mainMod .. " + period", hl.dsp.layout("colresize +conf"))
hl.bind(mainMod .. " + comma", hl.dsp.layout("colresize -conf"))

hl.bind(mainMod .. " + SHIFT + period", hl.dsp.layout("swapcol r"))
hl.bind(mainMod .. " + SHIFT + comma", hl.dsp.layout("swapcol l"))

hl.bind(mainMod .. " + G", hl.dsp.layout("promote"))
hl.bind(mainMod .. " + SHIFT + G", hl.dsp.layout("fit visible"))

-- Laptop multimedia keys for volume and LCD brightness
hl.bind(
	"XF86AudioRaiseVolume",
	hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioLowerVolume",
	hl.dsp.exec_cmd("wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd("wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle"),
	{ locked = true, repeating = true }
)
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%+"), { locked = true, repeating = true })
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl -e4 -n2 set 5%-"), { locked = true, repeating = true })

-- Requires playerctl
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPause", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPlay", hl.dsp.exec_cmd("playerctl play-pause"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })

--------------------------------
---- WINDOWS AND WORKSPACES ----
--------------------------------

-- See https://wiki.hypr.land/Configuring/Basics/Window-Rules/
-- and https://wiki.hypr.land/Configuring/Basics/Workspace-Rules/

-- Example window rules that are useful

local suppressMaximizeRule = hl.window_rule({
	-- Ignore maximize requests from all apps. You'll probably like this.
	name = "suppress-maximize-events",
	match = { class = ".*" },

	suppress_event = "maximize",
})
-- suppressMaximizeRule:set_enabled(false)

hl.window_rule({
	-- Fix some dragging issues with XWayland
	name = "fix-xwayland-drags",
	match = {
		class = "^$",
		title = "^$",
		xwayland = true,
		float = true,
		fullscreen = false,
		pin = false,
	},

	no_focus = true,
})

-- Layer rules also return a handle.
-- local overlayLayerRule = hl.layer_rule({
--     name  = "no-anim-overlay",
--     match = { namespace = "^my-overlay$" },
--     no_anim = true,
-- })
-- overlayLayerRule:set_enabled(false)

-- SwayNC slides in/out
hl.layer_rule({
	name = "swaync-slide",
	match = {
		namespace = "^(swaync-notification-window|swaync-control-center)$",
	},
	animation = "slide",
	ignore_alpha = 0,
})

-- Rofi gets blur + pop-in
hl.layer_rule({
	name = "rofi-popin",
	match = {
		namespace = "^rofi$",
	},
	animation = "popin",
	blur = true,
	ignore_alpha = 0,
})

-- Hyprland-run windowrule
hl.window_rule({
	name = "move-hyprland-run",
	match = { class = "hyprland-run" },

	move = "20 monitor_h-120",
	float = true,
})
