-- Generated by nwg-displays on 2026-08-15 at 15:16:24. Do not edit manually.

hl.monitor({
    output = "HDMI-A-1",
    mode = "1920x1080@165.0",
    position = "2560x247",
    scale = 1.0
})
hl.monitor({
    output = "DP-1",
    mode = "2560x1440@200.0",
    position = "0x0",
    scale = 1
})
